-- Criar usuário diretamente no banco de dados Supabase Auth
-- Inserir na tabela auth.users
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  confirmed_at,
  confirmation_token,
  recovery_token,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current_deadline,
  email_change_token_new_deadline
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  gen_random_uuid(),
  'authenticated',
  'authenticated',
  'Bruno@move.com',
  crypt('15002031', gen_salt('bf')), -- Hash da senha usando bcrypt
  now(),
  now(),
  now(),
  '',
  '',
  '',
  '',
  null,
  '',
  0,
  null,
  '{"provider": "email", "providers": ["email"]}',
  '{"nome_completo": "Bruno Santos", "tipo_usuario": "admin"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  null,
  null
)
RETURNING id;