// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kikanqxtcsrourtqbqpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtpa2FucXh0Y3Nyb3VydHFicXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDc5NDEsImV4cCI6MjA3MDA4Mzk0MX0.z4sZ9Pjgx_yONiKwyN9lURSxRbtRMpcq3cel4InFzlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});